// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is generated automatically from the docs folder, ordered by the
 * `sidebar_position` front matter in each file.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  handbookSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
